name: ETL CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-and-test:
    runs-on: windows-latest

    steps:
      # Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest black flake8

      # Run Black (check formatting only, don’t reformat automatically)
      - name: Run Black
        run: black --check .

      # Run Flake8 (linting)
      - name: Run Flake8
        run: flake8 .

      # Run pytest
      - name: Run pytest
        run: pytest -v
